---
title: "FP_Stat184"
author: "Bryan Xiao, Daiwik Kashyap"
format: 
  pdf:
    embed-resources: true
    toc: true
editor: visual
---

```{r}
#| label: Libraries & Datasets
#| echo: false
#| message: false
# Loading Libraries
library(tidyverse)
library(googlesheets4)
library(ggplot2)
library(dcData)
library(knitr)
library(tinytex)
library(stringr)

# Loading Datasets
data <- read.csv("~/GitHub/Sec4_FP_BryanXiao_DaiwikKashyap/data/data.csv", header=TRUE, row.names=1)
steam <- read.csv("~/GitHub/Sec4_FP_BryanXiao_DaiwikKashyap/data/steam.csv")
```

```{r}
#| label: Data Wrangling
#| echo: false
#| message: false

MostPlayedDataset <- read.csv("~/GitHub/Sec4_FP_BryanXiao_DaiwikKashyap/data/data.csv", header=TRUE, row.names=1)
SteamStoreDataset <- read.csv("~/GitHub/Sec4_FP_BryanXiao_DaiwikKashyap/data/steam.csv")

MostPlayedDataset$All_time.peak <- str_replace_all(MostPlayedDataset$All_time.peak, ",", "")
MostPlayedDataset$All_time.peak <- as.numeric(as.character(MostPlayedDataset$All_time.peak))

SteamStoreDataset <- SteamStoreDataset %>%
  rename(Name = name)

MergedData <- merge(SteamStoreDataset, MostPlayedDataset)

MergedDataTidy <- MergedData %>% 
  arrange(desc(All_time.peak), .by_group = TRUE) %>%
  select("Name", "genres", "All_time.peak") %>%
  rename(
    Genres = genres,
    All_Time_Peak = All_time.peak
  ) %>%
  slice(1:200) %>%
  separate(
    col = "Genres",
    sep = ";",
    into = c("Genre 1", "Genre 2", "Genre 3")
  )

```

```{r codeAppendix, ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE}
```
